import './globals.css'
import Head from 'next/head'

export const metadata = {
  title: 'Name - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head/>
      <body>{children}</body>
    </html>
  )
}
